### ISSUE TITLE
SqlServer Create: Not checking error causing panic

### ISSUE THREAD

**Issue by estenssoros** [go-gorm/sqlserver#4]
I am getting a panic response when trying to use Create. It looks like this is because the result is nil and we are asking for the affected rows. I'm guessing this is due to the error not getting checked at L166

https://github.com/go-gorm/sqlserver/blob/57efdbfd63e9a5905a3a4e14c831ec04d6c29a45/create.go#L166

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13fcd02]

goroutine 1 [running]:
gorm.io/driver/sqlserver.Create(0xc00071bbc0)
	/Users/estenssoros/go/pkg/mod/gorm.io/driver/sqlserver@v1.0.3/create.go:167 +0x1762
gorm.io/gorm.(*processor).Execute(0xc000716640, 0xc00071bbc0)
	/Users/estenssoros/go/pkg/mod/gorm.io/gorm@v1.20.0/callbacks.go:101 +0x21d
gorm.io/gorm.(*DB).Create(0xc000226720, 0x174a4a0, 0xc00082e0e0, 0xc00082e0e0)
	/Users/estenssoros/go/pkg/mod/gorm.io/gorm@v1.20.0/finisher_api.go:19 +0xa7
github.com/seaspancode/moneys/cmd.createRevenueBlocks(0xc000226720, 0x4, 0xc00084bc80)
```

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
